## 속성 attribute 파악

In [6]:
from tensorflow import random
from keras import Sequential
from keras.layers import Dense
import numpy as np


In [15]:
x = np.array([[2,0], [3,1], [4,0], [5,1], [6,2], [7,3], [8,1]])
y = np.array([47, 86, 65, 92, 61, 60, 55])

In [16]:
random.set_seed(42)

In [7]:
md = Sequential()
md.add(Dense(15, activation='relu', input_shape=(2,)))
md.add(Dense(1, activation='linear'))
md.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 15)                45        
                                                                 
 dense_1 (Dense)             (None, 1)                 16        
                                                                 
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


### 모델 속성 확인

In [9]:
md.layers
md.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 15) dtype=float32, numpy=
 array([[ 0.02734363,  0.34478903,  0.14032918, -0.1897498 , -0.49163085,
          0.26149434,  0.28977156, -0.26379898,  0.15603113,  0.2710427 ,
         -0.01281178,  0.3830058 ,  0.08915114,  0.5354185 , -0.483238  ],
        [ 0.2200644 ,  0.08569252,  0.52577317,  0.48205304,  0.54442525,
         -0.12708437, -0.25144964,  0.29066628, -0.58843184,  0.44045472,
          0.40627134, -0.57291454,  0.42310023, -0.47557604,  0.07020462]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(15,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(15, 1) dtype=float32, numpy=
 array([[ 0.43447644],
        [ 0.5098652 ],
        [ 0.5814038 ],
        [-0.29665485],
        [ 0.17227137],
        [-0.31666064],
        [ 0.02535117],
        [-0.31191456],
        [ 0.4346723 ],
        [ 0.46384758],
       

In [14]:
md.layers[0].get_weights()

[array([[ 0.02734363,  0.34478903,  0.14032918, -0.1897498 , -0.49163085,
          0.26149434,  0.28977156, -0.26379898,  0.15603113,  0.2710427 ,
         -0.01281178,  0.3830058 ,  0.08915114,  0.5354185 , -0.483238  ],
        [ 0.2200644 ,  0.08569252,  0.52577317,  0.48205304,  0.54442525,
         -0.12708437, -0.25144964,  0.29066628, -0.58843184,  0.44045472,
          0.40627134, -0.57291454,  0.42310023, -0.47557604,  0.07020462]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       dtype=float32)]