# 넘파이 학습
- 배열(array): 연속된 메모리 공간, __동일한 데이터타입__
- C 언어로 구현된 파이썬 라이브러리
- 고성능의 수치계산을 위해 제작된 라이브러리
- loop 프로그래밍 없이 전체 배열에 대해 표준 수학 함수 빠른 속도로 수행
- 파이썬에 배열(array) 기능 제공 라이브러리
- 대량의 데이터에 대한 고급 수학적 및 기타 유형 작업
- 머신러닝/딥러닝 패키지 Scikit-lern, Tensorflow, PyTorch, Keras 등에서도 내부 데이터 저장 및 수치계산 사용되는 패키지


In [1]:
# 버젼 확인
import pandas as pd 
import numpy as np

np.__version__

'1.23.0'

## 배열(array)
- 순차적으로 데이터를 저장하는 자료형
- 서로 연관있는 데이터를 하나의 변수명으로 저장
- 같은 타입의 변수들로 이루어진 유한집합으로 정의
- __원소개수 변경 불가__

- 리스트: 동적 공간에 다양한 데이터 타입 저장, 속도가 느리고 메모리를 많이 차지

### ndarray 클래스
- 다차원 배열(n-dim array)

In [4]:
# ndarray 객체 생성하기 -> numpy.array()
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [5]:
type(arr1)

numpy.ndarray

In [9]:
# ndarray 객체의 속성 확인하기
# 객체변수명.속성명
# ndim -> 차원, shape -> 형태 ( 면, 행, 열)
# dtype -> 데이터 타입
# itemsize -> 배열 요소의 바이트 크기, size -> 배열 요소의 개수
print(arr1.ndim, arr1.shape, arr1.dtype, arr1.itemsize, arr1.size, sep= '\n')

1
(3,)
int32
4
3


In [14]:
# 배열의 요소=아이템=원소 접근하기
# 0-base 인덱스 자동 지정 -> 객체변수명[인덱스]
print(f'객체변수명: {arr1}') 
print(f'객체변수명: {arr1[0]}') 
print(f'객체변수명: {arr1[1]}')



객체변수명: [1 2 3]
객체변수명: 1
객체변수명: 2


In [20]:
arr1.T

array([1, 4, 9])

In [24]:
# 모든 값을 0으로 채워서 ndarray 객체 생성 함수 -> zeros()
arr2 = np.array([0,0,0,0])
arr2 = np.zeros(4)
arr2

array([0., 0., 0., 0.])

In [27]:
# 모든 값을 1으로 채워서 ndarray 객체 생성 함수 -> ones()
arr2 = np.ones(shape=(3,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
type(arr2[0][0])

numpy.float64

In [32]:
arr2 = np.ones(shape=(3,4), dtype='int64')
arr2
print(arr2.ndim, arr2.shape, arr2.dtype, arr2.itemsize, arr2.size, sep= '\n')

2
(3, 4)
int64
8
12


In [35]:
# full 함수
np.full(shape=(3,4), fill_value=-1)

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [37]:
# 초기화하지 않고ndarray 객체 생성 -> numpy.empty()
arr3 = np.empty((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# linspace, logspace
# 2차원형태의 array객체 생성
# 2차원 배열 -> 1차원배열 : flatten, ravel
arr3.flatten()

array([0., 0., 0., 0., 0., 0.])

In [41]:
arr3.shape, arr3.ndim

((2, 3), 2)

In [43]:
# 1차원 -> 다른 차원으로 변경 reshape()

arr4 = arr3.reshape((3,2))
arr4

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
arr3.reshape((2, 3,1))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [51]:
# hstack, vstack, dstack()
# 깊이 , 채널, 차원
# 행의 개수를 모를때, 행 자리에 -1를 주면 된다. 그러면 알아서 계산
arr4 = arr3.reshape(-1, 6)
arr4

array([[0., 0., 0., 0., 0., 0.]])

In [ ]:
# 곱셈으로 dot, matmul, @ 가 쓰인다.
